services:
  app:
    build:
      context: .
      target: production
    ports:
      - "80:80"
    volumes:
      - ./config/data/sqlite/products.sqlite:/var/www/html/config/data/sqlite/products.sqlite
    environment:
      - APP_ENV=development
      - BASE_PATH=/cosmos
      - API_KEY=YOUR_API_KEY # Please replace with your actual API key
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - CORS_ALLOWED_ORIGINS=*
      - RATE_LIMIT_REQUESTS=100
      - RATE_LIMIT_WINDOW=3600
    networks:
      - app-network
    depends_on:
      - redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/cosmos/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  dev:
    build:
      context: .
      target: base
    ports:
      - "8081:80"
    volumes:
      - .:/var/www/html
      - ./config/php.ini:/usr/local/etc/php/php.ini:ro
    environment:
      - APP_ENV=development
      - BASE_PATH=/cosmos
    networks:
      - app-network
    depends_on:
      - redis
    user: root

  redis:
    image: "redis:alpine"
    networks:
      - app-network
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  app-network:
    driver: bridge

volumes:
  redis-data:
