services:
  app:
    build:
      context: .
      target: production
    ports:
      - "8080:80"
    volumes:
      - ./config/data/sqlite/products.sqlite:/var/www/html/config/products.sqlite
    environment:
      - APP_ENV=production

  dev:
    build:
      context: .
      target: base
    ports:
      - "8081:80"
    volumes:
      - .:/var/www/html
    environment:
      - APP_ENV=development
